language: en-US
reviews:
  profile: chill
  poem: false
  path_filters: []
  path_instructions:
    - path: "dashboard-deployments/**"
      instructions: >-
        This directory contains server-side dashboard examples for visualizing data from 
        FixedIT Data Agent running on Axis devices. These are primarily for DevOps/IT 
        professionals comfortable with deploying Grafana dashboards and InfluxDB servers. 
        Some dashboards work directly with bundled agent configurations, others can be 
        customized. Licensed under Elastic License 2.0. Review for deployment complexity, 
        dashboard usability, and proper licensing compliance. We should make sure that
        dashboards are portable and does not check in specific host names, or refer to
        other specific data from a single deployment.
    - path: "**/*.md"
      instructions: >-
        Documentation files should clearly communicate the dual audience: (1) server-side 
        dashboard users who want to keep agent with bundled configs, and (2) edge device 
        developers who want to customize agent behavior. Ensure examples and instructions 
        are appropriate for the intended skill level and use case. Since this is a public
        repository, we should not include any sensitive information, the instructions
        should be easily understandable for a wide audience, and we should avoid using
        any jargon or technical terms that are not commonly used.
    - path: "**/*"
      instructions: >-
        This repository serves FixedIT Data Agent users across a spectrum from plug-and-play 
        dashboard deployment to advanced edge device customization. Consider whether changes 
        maintain accessibility for both DevOps professionals (server-side focus) and 
        developers (edge customization focus). If new features are added or existing ones 
        changed significantly, ensure documentation clearly explains the intended audience 
        and usage level. We use prettier for formatting of common file formats like markdown,
        yaml, json, etc.
  auto_review:
    enabled: true
    auto_incremental_review: true
    base_branches: [".*"]
