{
 "title": "Device Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n  bucket: \"${bucket}\",\n  tag: \"host\",\n)"
    }
   },
   { "name": "unique_identifier", "query": "host" },
   { "name": "datasource", "query": "influxdb" },
   { "name": "bucket", "query": { "query": "buckets()" } }
  ]
 },
 "panels": [
  {
   "title": "Device Model Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "// Get the latest timestamp where product_full_name was reported for the selected camera\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  // Filter on measurement to get a consistent schema\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  // Create a stream for each device\n  |> group(columns: [\"${unique_identifier}\"])\n  // Sort and get the latest\n  |> sort(columns: [\"_time\"], desc: true)\n  |> first()\n  |> keep(columns: [\"${unique_identifier}\", \"product_full_name\"])"
    }
   ]
  },
  {
   "title": "Geo Tags",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  // Time range filter...\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\n  // Generic measurement just to access the tags...\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n\n  // Filter based on drop-downs\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n\n  // Sort and take the latest received tags for each device\n  |> group(columns: [\"${unique_identifier}\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n:1)\n\n  // Keep things we want only\n  |> keep(columns: [\"_time\", \"${unique_identifier}\", \"area\", \"geography\", \"region\", \"site\", \"type\", \"product_full_name\"])\n\n  // Flatten\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Device Type Tag Over Time",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\n  // Generic measurement just to access the tags. To reduce number of points,\n  // we also filter to one single core and field.\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"cpu\" and\n    r[\"cpu\"] == \"cpu-total\" and\n    r[\"_field\"] == \"usage_idle\"\n  )\n\n  // Filter for matching devices\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n\n  // Aggregate into time series windows to reduce number of returned data points\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n\n  // Keep timestamp, device and type\n  |> keep(columns: [\"_time\", \"${unique_identifier}\", \"type\"])\n\n  // Rename and remap to Grafana-friendly _time, _field, _value,\n  // that gets rid of the \"type <host>\" prefix in the visualization.\n  |> map(fn: (r) => ({\n    _time: r._time,\n    _field: r[\"${unique_identifier}\"],\n    _value: r[\"type\"]\n  }))\n\n  // Group per device (now _field)\n  |> group(columns: [\"_field\"])\n\n  // Sort by time\n  |> sort(columns: [\"_time\"])\n"
    }
   ]
  },
  { "title": "Device Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Device Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\n  |> group(columns: [\"${unique_identifier}\"]) // flatten tag sets for host\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "  from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"available\")\n  |> group(columns: [\"${unique_identifier}\"]) // flatten tag sets for host\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Free CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "  from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_idle\")\n  |> group(columns: [\"${unique_identifier}\", \"cpu\"]) // flatten tag sets for host\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  "
    }
   ]
  },
  {
   "title": "Free Flash Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "free = \nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"free\")\n  |> filter(fn: (r) => r[\"path\"] == \"/usr/local\")\n  |> group(columns: [\"${unique_identifier}\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"${unique_identifier}\"])\n  |> rename(columns: {_value: \"Free\"})\n\ntotal =\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\n  |> filter(fn: (r) => r[\"path\"] == \"/usr/local\")\n  |> group(columns: [\"${unique_identifier}\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"${unique_identifier}\"])\n  |> rename(columns: {_value: \"Total\"})\n\njoin(\n  tables: {free: free, total: total},\n  on: [\"_time\", \"${unique_identifier}\"]\n)\n"
    }
   ]
  },
  {
   "title": "Free SD Card Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "free = \nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"free\")\n  |> filter(fn: (r) => r[\"path\"] == \"/var/spool/storage/SD_DISK\")\n  |> group(columns: [\"${unique_identifier}\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"${unique_identifier}\"])\n  |> rename(columns: {_value: \"Free\"})\n\ntotal =\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\n  |> filter(fn: (r) => r[\"path\"] == \"/var/spool/storage/SD_DISK\")\n  |> group(columns: [\"${unique_identifier}\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"${unique_identifier}\"])\n  |> rename(columns: {_value: \"Total\"})\n\njoin(\n  tables: {free: free, total: total},\n  on: [\"_time\", \"${unique_identifier}\"]\n)\n"
    }
   ]
  },
  { "title": "Network Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Device IP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "  // Get latest local and external IP per device in one query\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  // Select both relevant measurements\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"local_ip_addresses\" or\n    r[\"_measurement\"] == \"external_ip\"\n  )\n  // Group by device and measurement\n  |> group(columns: [\"${unique_identifier}\", \"_measurement\"])\n  // Get the latest entry for each\n  |> last()\n  // Reshape for clarity\n  |> pivot(\n    rowKey: [\"${unique_identifier}\"],\n    columnKey: [\"_measurement\"],\n    valueColumn: \"_value\"\n  )\n  // Optional: Rename columns for clarity\n  |> rename(columns: {\n    local_ip_addresses: \"Local IPs\",\n    external_ip: \"External IP\"\n  })\n  |> keep(columns: [\"${unique_identifier}\", \"Local IPs\", \"External IP\"])"
    }
   ]
  },
  {
   "title": "DNS Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"internet_connectivity_dns\")\n  |> filter(fn: (r) => r[\"result\"] == \"success\")\n  |> filter(fn: (r) => r[\"_field\"] == \"query_time_ms\")\n  |> group(columns: [\"${unique_identifier}\"]) // flatten tag sets for host\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "DNS Connection OK",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"internet_connectivity_dns\")\n  // Map success to 1, others to 0\n  |> map(fn: (r) => ({\n    r with _value: if r[\"result\"] == \"success\" then 1 else 0\n  }))\n  |> group(columns: [\"${unique_identifier}\"])\n  // Calculate the mean for each block to reduce number of data points\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  }
 ]
}