{
 "title": "Overview of Devices",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "influxdb" },
   { "name": "bucket", "label": "Database", "query": { "query": "buckets()" } },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"${unique_identifier}\")"
    }
   },
   {
    "name": "geography",
    "label": "Geography",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"geography\")"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"region\")"
    }
   },
   {
    "name": "area",
    "label": "Area",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"area\")"
    }
   },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"site\")"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"type\")"
    }
   },
   { "name": "unique_identifier", "query": "host" },
   {
    "name": "model",
    "label": "Model Name",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"product_full_name\")"
    }
   },
   { "name": "device_details_uid", "query": "bekds38txl1j4c" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Report",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "// Get cameras with reported data in the selected interval\r\nfrom(bucket: \"${bucket}\")\r\n  // Filter on time\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  // Filter using variable selectors (supports All and multi-select)\r\n  |> filter(fn: (r) => r[\"area\"] =~ /${area:regex}/)\r\n  |> filter(fn: (r) => r[\"geography\"] =~ /${geography:regex}/)\r\n  |> filter(fn: (r) => r[\"region\"] =~ /${region:regex}/)\r\n  |> filter(fn: (r) => r[\"site\"] =~ /${site:regex}/)\r\n  |> filter(fn: (r) => r[\"type\"] =~ /${type:regex}/)\r\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\r\n  |> filter(fn: (r) => r[\"product_full_name\"] =~ /${model:regex}/)\r\n  // We cant flatten if the values are of different types, so we just\r\n  // filter for an arbitrary value that we know exists...\r\n  |> filter(fn: (r) =>\r\n    r[\"_measurement\"] == \"cpu\" and\r\n    r[\"cpu\"] == \"cpu-total\" and\r\n    r[\"_field\"] == \"usage_idle\"\r\n  )\r\n  // Group by device to merge to one time series per device\r\n  |> group(columns: [\"${unique_identifier}\"])\r\n  // Get the last data point for each device\r\n  |> last()\r\n  // Ungroup to prepare a flat output\r\n  |> group()\r\n  // Keep only timestamp and device identifier\r\n  |> keep(columns: [\"_time\", \"${unique_identifier}\"])\r\n  // Rename _time to seen\r\n  |> rename(columns: {_time: \"seen\"})"
    },
    {
     "query": "// Get latest external IP per camera in the selected interval\nfrom(bucket: \"${bucket}\")\n  // Filter on time\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // Filter using variable selectors (supports All and multi-select)\n  |> filter(fn: (r) => r[\"area\"] =~ /${area:regex}/)\n  |> filter(fn: (r) => r[\"geography\"] =~ /${geography:regex}/)\n  |> filter(fn: (r) => r[\"region\"] =~ /${region:regex}/)\n  |> filter(fn: (r) => r[\"site\"] =~ /${site:regex}/)\n  |> filter(fn: (r) => r[\"type\"] =~ /${type:regex}/)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"product_full_name\"] =~ /${model:regex}/)\n  // Filter on external IP measurement\n  |> filter(fn: (r) => r[\"_measurement\"] == \"external_ip\")\n  // Group by device to isolate each host\n  |> group(columns: [\"${unique_identifier}\"])\n  // Get the last reported external IP\n  |> last()\n  // Ungroup to flatten result set\n  |> group()\n  // Rename the value column and keep only relevant fields\n  |> rename(columns: {_value: \"external ip\"})\n  |> keep(columns: [\"${unique_identifier}\", \"external ip\"])\n"
    },
    {
     "query": "// Get latest local IP per camera in the selected interval\nfrom(bucket: \"${bucket}\")\n  // Filter on time\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // Filter using variable selectors (supports All and multi-select)\n  |> filter(fn: (r) => r[\"area\"] =~ /${area:regex}/)\n  |> filter(fn: (r) => r[\"geography\"] =~ /${geography:regex}/)\n  |> filter(fn: (r) => r[\"region\"] =~ /${region:regex}/)\n  |> filter(fn: (r) => r[\"site\"] =~ /${site:regex}/)\n  |> filter(fn: (r) => r[\"type\"] =~ /${type:regex}/)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"product_full_name\"] =~ /${model:regex}/)\n  // Filter on local IP measurement\n  |> filter(fn: (r) => r[\"_measurement\"] == \"local_ip_addresses\")\n  // Group by device to isolate each host\n  |> group(columns: [\"${unique_identifier}\"])\n  // Get the last reported local IP\n  |> last()\n  // Ungroup to flatten result set\n  |> group()\n  // Rename the value column and keep only relevant fields\n  |> rename(columns: {_value: \"local ip\"})\n  |> keep(columns: [\"${unique_identifier}\", \"local ip\"])\n"
    },
    {
     "query": "// Get latest internet latency per camera in the selected interval\nfrom(bucket: \"${bucket}\")\n  // Filter on time\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // Filter using variable selectors (supports All and multi-select)\n  |> filter(fn: (r) => r[\"area\"] =~ /${area:regex}/)\n  |> filter(fn: (r) => r[\"geography\"] =~ /${geography:regex}/)\n  |> filter(fn: (r) => r[\"region\"] =~ /${region:regex}/)\n  |> filter(fn: (r) => r[\"site\"] =~ /${site:regex}/)\n  |> filter(fn: (r) => r[\"type\"] =~ /${type:regex}/)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"product_full_name\"] =~ /${model:regex}/)\n  // Filter on internet connectivity measurement and field\n  |> filter(fn: (r) => r[\"_measurement\"] == \"internet_connectivity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"response_time\")\n  // Group by device to isolate each host\n  |> group(columns: [\"${unique_identifier}\"])\n  // Get the last reported response time\n  |> last()\n  // Ungroup to flatten result set\n  |> group()\n  // Rename the value column and keep only relevant fields\n  |> rename(columns: {_value: \"internet latency\"})\n  |> keep(columns: [\"${unique_identifier}\", \"internet latency\"])\n"
    },
    {
     "query": "// Get latest local IP per camera in the selected interval\nfrom(bucket: \"${bucket}\")\n  // Filter on time\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // Filter using variable selectors (supports All and multi-select)\n  |> filter(fn: (r) => r[\"area\"] =~ /${area:regex}/)\n  |> filter(fn: (r) => r[\"geography\"] =~ /${geography:regex}/)\n  |> filter(fn: (r) => r[\"region\"] =~ /${region:regex}/)\n  |> filter(fn: (r) => r[\"site\"] =~ /${site:regex}/)\n  |> filter(fn: (r) => r[\"type\"] =~ /${type:regex}/)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"product_full_name\"] =~ /${model:regex}/)\n  // Filter on a single meaurement to make the schema aligned\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  // Group by device to isolate each host\n  |> group(columns: [\"${unique_identifier}\"])\n  // Get the last report\n  |> last()\n  // Ungroup to flatten result set\n  |> group()\n  // Keep only host and device model\n  |> keep(columns: [\"${unique_identifier}\", \"product_full_name\"])\n  |> rename(columns: {\n    product_full_name: \"product full name\"\n  })"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"area\"] =~ /${area:regex}/)\n  |> filter(fn: (r) => r[\"geography\"] =~ /${geography:regex}/)\n  |> filter(fn: (r) => r[\"region\"] =~ /${region:regex}/)\n  |> filter(fn: (r) => r[\"site\"] =~ /${site:regex}/)\n  |> filter(fn: (r) => r[\"type\"] =~ /${type:regex}/)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"product_full_name\"] =~ /${model:regex}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> group(columns: [\"${unique_identifier}\"])\n  |> last()\n  |> group()\n  |> keep(columns: [\"${unique_identifier}\", \"firmware_version\"])\n  |> rename(columns: {\n    \"${unique_identifier}\": \"host\",\n    firmware_version: \"firmware version\"\n  })\n"
    }
   ]
  },
  {
   "title": "AXIS OS Changes",
   "type": "state-timeline",
   "description": "AXIS OS Changes",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\n  // Generic measurement just to access the tags. To reduce number of points,\n  // we also filter to one single core and field.\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"cpu\" and\n    r[\"cpu\"] == \"cpu-total\" and\n    r[\"_field\"] == \"usage_idle\" and\n\n    // Only show the ones that are reporting firmware_version\n    exists r[\"firmware_version\"] and\n\n    // Applied filters\n    (r[\"area\"] =~ /${area:regex}/) and\n    (r[\"geography\"] =~ /${geography:regex}/) and\n    (r[\"region\"] =~ /${region:regex}/) and\n    (r[\"site\"] =~ /${site:regex}/) and\n    (r[\"type\"] =~ /${type:regex}/) and\n    (r[\"${unique_identifier}\"] =~ /${device:regex}/) and\n    (r[\"product_full_name\"] =~ /${model:regex}/)\n  )\n\n  // Aggregate into time series windows to reduce number of returned data points\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false)\n\n  // Keep timestamp, device and firmware_version\n  |> keep(columns: [\"_time\", \"${unique_identifier}\", \"firmware_version\"])\n\n  // Rename and remap to Grafana-friendly _time, _field, _value,\n  // that gets rid of the \"firmware_version <host>\" prefix in the visualization.\n  |> map(fn: (r) => ({\n    _time: r._time,\n    _field: r[\"${unique_identifier}\"],\n    _value: r[\"firmware_version\"]\n  }))\n\n  // Group per device (now in _field)\n  |> group(columns: [\"_field\"])\n\n  // Sort by time\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "CPU and RAM trends",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  // Selected time span\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // Filter based on drop-downs\n  |> filter(fn: (r) => r[\"area\"] =~ /${area:regex}/)\n  |> filter(fn: (r) => r[\"geography\"] =~ /${geography:regex}/)\n  |> filter(fn: (r) => r[\"region\"] =~ /${region:regex}/)\n  |> filter(fn: (r) => r[\"site\"] =~ /${site:regex}/)\n  |> filter(fn: (r) => r[\"type\"] =~ /${type:regex}/)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"product_full_name\"] =~ /${model:regex}/)\n  // Filter out the fields we are interested in\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_idle\")\n  // One time series for each device\n  |> group(columns: [\"${unique_identifier}\"])\n  // Invert to CPU load instead of idle\n  |> map(fn: (r) => ({ r with _value: 100.0 - r._value }))\n  // Aggregate in blocks to reduce number of data points\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  // Selected time span\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // Filter based on drop-downs\n  |> filter(fn: (r) => r[\"area\"] =~ /${area:regex}/)\n  |> filter(fn: (r) => r[\"geography\"] =~ /${geography:regex}/)\n  |> filter(fn: (r) => r[\"region\"] =~ /${region:regex}/)\n  |> filter(fn: (r) => r[\"site\"] =~ /${site:regex}/)\n  |> filter(fn: (r) => r[\"type\"] =~ /${type:regex}/)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"product_full_name\"] =~ /${model:regex}/)\n  // Filter out the fields we are interested in\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  // One time series for each device\n  |> group(columns: [\"${unique_identifier}\"])\n  // Aggregate in blocks to reduce number of data points\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  { "title": "${device}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "repeat": "device" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  // Filter on time\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // Filter on the right device. Since this visual will be repeated, the\n  // device variable will always contain the right value and only one,\n  // so we do not need to do regexp here..\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] == \"${device}\")\n  // Filter on the field we want\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\n  // Group by device to merge multiple tagsets\n  |> group(columns: [\"${unique_identifier}\"])\n  // Get the last sample\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  // Filter on time\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // Filter on the right device. Since this visual will be repeated,\n  // the device variable will always contain the right value and only one,\n  // so we do not need to do regexp here..\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] == \"${device}\")\n  // Filter on the measurement and field we want\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_active\")\n  // Group by device to merge multiple tagsets\n  |> group(columns: [\"${unique_identifier}\"])\n  // Get the last sample\n  |> last()\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"n_cpus\")\n  |> filter(fn: (r) => r[\"host\"] == \"${device}\")\n|> last()"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  // Filter on time\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // Filter on the right device. Since this visual will be repeated,\n  // the device variable will always contain the right value and only one,\n  // so we do not need to do regexp here..\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] == \"${device}\")\n  // Filter on the measurement and field we want\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  // Group by device to merge multiple tagsets\n  |> group(columns: [\"${unique_identifier}\"])\n  // Get the last sample\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  // Filter on time\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // Filter on the right device. Since this visual will be repeated,\n  // the device variable will always contain the right value and only one,\n  // so we do not need to do regexp here..\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] == \"${device}\")\n  // Filter on the measurement, field, and specific path we want\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> filter(fn: (r) => r[\"path\"] == \"/usr/local\")\n  // Group by device to merge multiple tagsets\n  |> group(columns: [\"${unique_identifier}\"])\n  // Get the last sample\n  |> last()\n"
    }
   ]
  },
  {
   "title": "SD Card",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  // Filter on time\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // Filter on the right device. Since this visual will be repeated,\n  // the device variable will always contain the right value and only one,\n  // so we do not need to do regexp here..\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] == \"${device}\")\n  // Filter on the measurement, field, and specific path we want\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> filter(fn: (r) => r[\"path\"] == \"/var/spool/storage/SD_DISK\")\n  // Group by device to merge multiple tagsets\n  |> group(columns: [\"${unique_identifier}\"])\n  // Get the last sample\n  |> last()\n"
    }
   ]
  }
 ]
}