{
 "title": "System Overview",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "influxdb" },
   { "name": "bucket", "label": "Database", "query": { "query": "buckets()" } },
   {
    "name": "geography",
    "label": "Geography",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"geography\")"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"region\")"
    }
   },
   {
    "name": "area",
    "label": "Area",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"area\")"
    }
   },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"site\")"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"type\")"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"${unique_identifier}\")"
    }
   },
   { "name": "unique_identifier", "query": "host" },
   {
    "name": "model",
    "label": "Model Name",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"product_full_name\")"
    }
   },
   { "name": "outlier_count", "label": "K-Outliers", "query": "1,2,3,4,5,10,50" },
   { "name": "device_details_uid", "query": "bekds38txl1j4c" }
  ]
 },
 "panels": [
  {
   "title": "Device Count",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> keep(columns: [\"host\"])\n  |> group()\n  |> distinct(column: \"host\")\n  |> count(column: \"_value\")\n  |> rename(columns: {_value: \"total\"})\n  |> yield(name: \"all\")\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"area\"] =~ /${area:regex}/)\n  |> filter(fn: (r) => r[\"geography\"] =~ /${geography:regex}/)\n  |> filter(fn: (r) => r[\"region\"] =~ /${region:regex}/)\n  |> filter(fn: (r) => r[\"site\"] =~ /${site:regex}/)\n  |> filter(fn: (r) => r[\"type\"] =~ /${type:regex}/)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"product_full_name\"] =~ /${model:regex}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> keep(columns: [\"host\"])\n  |> group()\n  |> distinct(column: \"host\")\n  |> count(column: \"_value\")\n  |> rename(columns: {_value: \"selected\"})\n  |> yield(name: \"filtered\")"
    }
   ]
  },
  {
   "title": "Missing Devices",
   "type": "table",
   "description": "Known devices that does not have any data during this time span.",
   "gridPos": { "h": 11, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"array\"\n\n// Get cameras with reported data in the selected interval\nreal_data = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"cpu\" and\n    r[\"cpu\"] == \"cpu-total\" and\n    r[\"_field\"] == \"usage_idle\" and\n    r[\"area\"] =~ /${area:regex}/ and\n    r[\"geography\"] =~ /${geography:regex}/ and\n    r[\"region\"] =~ /${region:regex}/ and\n    r[\"site\"] =~ /${site:regex}/ and\n    r[\"type\"] =~ /${type:regex}/ and\n    r[\"${unique_identifier}\"] =~ /${device:regex}/ and\n    r[\"product_full_name\"] =~ /${model:regex}/\n  )\n  |> group(columns: [\"host\"])\n  |> last()\n  |> group()\n  |> keep(columns: [\"_time\", \"host\"])\n  |> rename(columns: {_time: \"seen\"})\n  |> map(fn: (r) => ({ r with in_interval: true })) // Add extra field for easier identification\n\n// Dummy fallback row (ensures structure exists even if real data is empty)\nfake_row = array.from(rows: [\n  {\n    host: \"dummy_device\",\n    seen: time(v: 0),\n    in_interval: true,\n    dummy: 1\n  }\n])\n\n// Combine real data with dummy row\nunion(tables: [real_data, fake_row])"
    },
    {
     "query": "import \"influxdata/influxdb/schema\"\n\n// Step 1: Get all known hosts\nhosts = schema.tagValues(\n  bucket: \"${bucket}\",\n  tag: \"host\"\n)\n  |> rename(columns: {_value: \"host\"})\n  |> map(fn: (r) => ({ r with known: true }))\n\n// Step 2: Get real data to apply tag-based filters\nfiltered_hosts = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"cpu\" and\n    r[\"cpu\"] == \"cpu-total\" and\n    r[\"_field\"] == \"usage_idle\" and\n    (exists r[\"area\"] and r[\"area\"] =~ /${area:regex}/) and\n    (exists r[\"geography\"] and r[\"geography\"] =~ /${geography:regex}/) and\n    (exists r[\"region\"] and r[\"region\"] =~ /${region:regex}/) and\n    (exists r[\"site\"] and r[\"site\"] =~ /${site:regex}/) and\n    (exists r[\"type\"] and r[\"type\"] =~ /${type:regex}/) and\n    (exists r[\"${unique_identifier}\"] and r[\"${unique_identifier}\"] =~ /${device:regex}/) and\n    (exists r[\"product_full_name\"] and r[\"product_full_name\"] =~ /${model:regex}/)\n  )\n  |> keep(columns: [\"host\"])\n  |> group()\n  |> distinct(column: \"host\")\n\n// Step 3: Join to retain only filtered hosts from schema list\njoin(\n  tables: {all: hosts, filtered: filtered_hosts},\n  on: [\"host\"]\n)\n"
    },
    {
     "query": "// Get last timestamp from a host (check the last 3 months back)\nfrom(bucket: \"${bucket}\")\n  |> range(start: -90d)\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"cpu\" and\n    r[\"cpu\"] == \"cpu-total\" and\n    r[\"_field\"] == \"usage_idle\" and\n    r[\"area\"] =~ /${area:regex}/ and\n    r[\"geography\"] =~ /${geography:regex}/ and\n    r[\"region\"] =~ /${region:regex}/ and\n    r[\"site\"] =~ /${site:regex}/ and\n    r[\"type\"] =~ /${type:regex}/ and\n    r[\"${unique_identifier}\"] =~ /${device:regex}/ and\n    r[\"product_full_name\"] =~ /${model:regex}/\n  )\n  |> group(columns: [\"host\"])\n  |> last()\n  |> group()\n  |> keep(columns: [\"_time\", \"host\"])\n  |> rename(columns: {_time: \"last seen\"})\n  |> map(fn: (r) => ({ r with seen_earlier: true })) // Add extra field for easier identification"
    }
   ]
  },
  {
   "title": "New Devices",
   "type": "table",
   "description": "New devices that did not exist before the start of the selected time span.",
   "gridPos": { "h": 11, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "// Get cameras with reported data in the selected interval\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => (\n    r[\"_measurement\"] == \"cpu\" and r[\"cpu\"] == \"cpu-total\" and r[\"_field\"] == \"usage_idle\"\n  ))\n  |> group(columns: [\"host\"])\n  |> first()\n  |> group()\n  |> keep(columns: [\"_time\", \"host\"])\n  |> rename(columns: {_time: \"first seen\"})\n  |> map(fn: (r) => ({ r with in_interval: true })) // Add extra field for easier identification"
    },
    {
     "query": "import \"array\"\nimport \"experimental\"\n\n// Make a query the last year before the selected interval starts,\n// that way we can find devices that was now known before the start of this\n// interval.\nbefore_data = from(bucket: \"${bucket}\")\n  |> range(start: experimental.subDuration(from: v.timeRangeStart, d: 365d), stop: v.timeRangeStart) // Before the interval starts\n  |> filter(fn: (r) => (\n    r[\"_measurement\"] == \"cpu\" and r[\"cpu\"] == \"cpu-total\" and r[\"_field\"] == \"usage_idle\"\n  ))\n  |> group(columns: [\"host\"])\n  |> last()\n  |> group()\n  |> keep(columns: [\"_time\", \"host\"])\n  |> map(fn: (r) => ({ r with seen_earlier: true })) // Add extra field for easier identification\n\n// Dummy fallback row to ensure structure\nbefore_dummy =\n  array.from(rows: [{\n    host: \"dummy_device\",\n    _time: time(v: 0),\n    seen_earlier: true,\n    dummy: 1\n  }])\n\n// Combine real before data with fallback\nunion(tables: [before_data, before_dummy])"
    }
   ]
  },
  {
   "title": "Outliers",
   "type": "table",
   "description": "Top k:\n* Highest load1\n* Highest load15\n* Shortest uptime\n* Highest memory used\n* Most flash storage (built in) used\n* Most SD card storage used",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "metric_to_use = \"load1\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\n  // 1. Apply metadata filters first (only if fields exist)\n  |> filter(fn: (r) => r[\"area\"] =~ /${area:regex}/)\n  |> filter(fn: (r) => r[\"geography\"] =~ /${geography:regex}/)\n  |> filter(fn: (r) => r[\"region\"] =~ /${region:regex}/)\n  |> filter(fn: (r) => r[\"site\"] =~ /${site:regex}/)\n  |> filter(fn: (r) => r[\"type\"] =~ /${type:regex}/)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"product_full_name\"] =~ /${model:regex}/)\n\n  // 2. Then filter for the metric of interest\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"system\" and\n    r[\"_field\"] == metric_to_use\n  )\n\n  // 3. Aggregate, format, and limit\n  |> group(columns: [\"host\"])\n  |> mean()\n  |> group()\n  |> rename(columns: {_value: metric_to_use})\n  |> keep(columns: [\"host\", metric_to_use])\n  |> sort(columns: [metric_to_use], desc: true)\n  |> limit(n: ${outlier_count})\n"
    },
    {
     "query": "metric_to_use = \"load15\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\n  // 1. Metadata filters (only if fields exist)\n  |> filter(fn: (r) => r[\"area\"] =~ /${area:regex}/)\n  |> filter(fn: (r) => r[\"geography\"] =~ /${geography:regex}/)\n  |> filter(fn: (r) => r[\"region\"] =~ /${region:regex}/)\n  |> filter(fn: (r) => r[\"site\"] =~ /${site:regex}/)\n  |> filter(fn: (r) => r[\"type\"] =~ /${type:regex}/)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"product_full_name\"] =~ /${model:regex}/)\n\n  // 2. Metric filtering\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"system\" and\n    r[\"_field\"] == metric_to_use\n  )\n\n  // 3. Aggregation and formatting\n  |> group(columns: [\"host\"])\n  |> mean()\n  |> group()\n  |> rename(columns: {_value: metric_to_use})\n  |> keep(columns: [\"host\", metric_to_use])\n\n  // 4. Sort and limit\n  |> sort(columns: [metric_to_use], desc: true)\n  |> limit(n: ${outlier_count})\n"
    },
    {
     "query": "metric_to_use = \"uptime\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\n  // 1. Metadata filters (only apply if fields exist)\n  |> filter(fn: (r) => r[\"area\"] =~ /${area:regex}/)\n  |> filter(fn: (r) => r[\"geography\"] =~ /${geography:regex}/)\n  |> filter(fn: (r) => r[\"region\"] =~ /${region:regex}/)\n  |> filter(fn: (r) => r[\"site\"] =~ /${site:regex}/)\n  |> filter(fn: (r) => r[\"type\"] =~ /${type:regex}/)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"product_full_name\"] =~ /${model:regex}/)\n\n  // 2. Metric filter for uptime\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\" and r[\"_field\"] == metric_to_use)\n\n  // 3. Aggregate and format\n  |> group(columns: [\"host\"])\n  |> last() // Last reported uptime during the selected time span\n  |> group()\n  |> rename(columns: {_value: metric_to_use})\n  |> keep(columns: [\"host\", metric_to_use])\n  |> sort(columns: [metric_to_use], desc: false) // Ascending = lowest uptime\n  |> limit(n: ${outlier_count})\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\n  // 1. Metadata filters (safe if tag missing)\n  |> filter(fn: (r) => r[\"area\"] =~ /${area:regex}/)\n  |> filter(fn: (r) => r[\"geography\"] =~ /${geography:regex}/)\n  |> filter(fn: (r) => r[\"region\"] =~ /${region:regex}/)\n  |> filter(fn: (r) => r[\"site\"] =~ /${site:regex}/)\n  |> filter(fn: (r) => r[\"type\"] =~ /${type:regex}/)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"product_full_name\"] =~ /${model:regex}/)\n\n  // 2. Metric filter\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"used_percent\")\n\n  // 3. Aggregation and formatting\n  |> group(columns: [\"host\"])\n  |> mean()\n  |> group()\n  |> rename(columns: {_value: \"memory used\"})\n  |> keep(columns: [\"host\", \"memory used\"])\n\n  // 4. Sort by memory used (descending = highest usage)\n  |> sort(columns: [\"memory used\"], desc: true)\n  |> limit(n: ${outlier_count})\n"
    },
    {
     "query": "metric_name = \"flash used\"\ndisk_path = \"/usr/local\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\n  // 1. Metadata filters\n  |> filter(fn: (r) => r[\"area\"] =~ /${area:regex}/)\n  |> filter(fn: (r) => r[\"geography\"] =~ /${geography:regex}/)\n  |> filter(fn: (r) => r[\"region\"] =~ /${region:regex}/)\n  |> filter(fn: (r) => r[\"site\"] =~ /${site:regex}/)\n  |> filter(fn: (r) => r[\"type\"] =~ /${type:regex}/)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"product_full_name\"] =~ /${model:regex}/)\n\n  // 2. Metric and path filter\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"disk\" and\n    r[\"_field\"] == \"used_percent\" and\n    r[\"path\"] == disk_path\n  )\n\n  // 3. Aggregate and format\n  |> group(columns: [\"host\"])\n  |> mean() // Mean over the selected time span\n  |> group()\n  |> rename(columns: {_value: metric_name})\n  |> keep(columns: [\"host\", metric_name])\n\n  // 4. Sort and limit\n  |> sort(columns: [metric_name], desc: true)\n  |> limit(n: ${outlier_count})\n"
    },
    {
     "query": "metric_name = \"sd card used\"\ndisk_path = \"/var/spool/storage/SD_DISK\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\n  // 1. Metadata filters\n  |> filter(fn: (r) => r[\"area\"] =~ /${area:regex}/)\n  |> filter(fn: (r) => r[\"geography\"] =~ /${geography:regex}/)\n  |> filter(fn: (r) => r[\"region\"] =~ /${region:regex}/)\n  |> filter(fn: (r) => r[\"site\"] =~ /${site:regex}/)\n  |> filter(fn: (r) => r[\"type\"] =~ /${type:regex}/)\n  |> filter(fn: (r) => r[\"${unique_identifier}\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r[\"product_full_name\"] =~ /${model:regex}/)\n\n  // 2. Metric and path filter\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"disk\" and\n    r[\"_field\"] == \"used_percent\" and\n    r[\"path\"] == disk_path\n  )\n\n  // 3. Aggregate and format\n  |> group(columns: [\"host\"])\n  |> mean() // Mean over the selected time span\n  |> group()\n  |> rename(columns: {_value: metric_name})\n  |> keep(columns: [\"host\", metric_name])\n\n  // 4. Sort and limit\n  |> sort(columns: [metric_name], desc: true)\n  |> limit(n: ${outlier_count})\n"
    }
   ]
  },
  {
   "title": "Average CPU / RAM / Disk Usage per Type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "cpu = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"cpu\" and\n    r._field == \"usage_idle\" and\n    r.cpu == \"cpu-total\" and\n    exists r.type and\n    r.type =~ /${type:regex}/ and\n    r[\"area\"] =~ /${area:regex}/ and\n    r[\"geography\"] =~ /${geography:regex}/ and\n    r[\"region\"] =~ /${region:regex}/ and\n    r[\"site\"] =~ /${site:regex}/ and\n    r[\"product_full_name\"] =~ /${model:regex}/ and\n    r[\"${unique_identifier}\"] =~ /${device:regex}/\n  )\n  |> map(fn: (r) => ({ r with _value: 100.0 - r._value }))\n  |> group(columns: [\"type\"])\n  |> mean()\n  |> map(fn: (r) => ({ r with metric: \"CPU Usage\" }))\n\nram = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"mem\" and\n    r._field == \"used_percent\" and\n    exists r.type and\n    r.type =~ /${type:regex}/ and\n    r[\"area\"] =~ /${area:regex}/ and\n    r[\"geography\"] =~ /${geography:regex}/ and\n    r[\"region\"] =~ /${region:regex}/ and\n    r[\"site\"] =~ /${site:regex}/ and\n    r[\"product_full_name\"] =~ /${model:regex}/ and\n    r[\"${unique_identifier}\"] =~ /${device:regex}/\n  )\n  |> group(columns: [\"type\"])\n  |> mean()\n  |> map(fn: (r) => ({ r with metric: \"RAM Usage\" }))\n\ndisk_usr_local = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"disk\" and\n    r._field == \"used_percent\" and\n    r.path == \"/usr/local\" and\n    exists r.type and\n    r.type =~ /${type:regex}/ and\n    r[\"area\"] =~ /${area:regex}/ and\n    r[\"geography\"] =~ /${geography:regex}/ and\n    r[\"region\"] =~ /${region:regex}/ and\n    r[\"site\"] =~ /${site:regex}/ and\n    r[\"product_full_name\"] =~ /${model:regex}/ and\n    r[\"${unique_identifier}\"] =~ /${device:regex}/\n  )\n  |> group(columns: [\"type\"])\n  |> mean()\n  |> map(fn: (r) => ({ r with metric: \"Disk /usr/local\" }))\n\ndisk_sd = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"disk\" and\n    r._field == \"used_percent\" and\n    r.path == \"/var/volatile/spool/storage/SD_DISK\" and\n    exists r.type and\n    r.type =~ /${type:regex}/ and\n    r[\"area\"] =~ /${area:regex}/ and\n    r[\"geography\"] =~ /${geography:regex}/ and\n    r[\"region\"] =~ /${region:regex}/ and\n    r[\"site\"] =~ /${site:regex}/ and\n    r[\"product_full_name\"] =~ /${model:regex}/ and\n    r[\"${unique_identifier}\"] =~ /${device:regex}/\n  )\n  |> group(columns: [\"type\"])\n  |> mean()\n  |> map(fn: (r) => ({ r with metric: \"Disk /SD_DISK\" }))\n\nunion(tables: [cpu, ram, disk_usr_local, disk_sd])\n  |> group()\n  |> pivot(rowKey: [\"type\"], columnKey: [\"metric\"], valueColumn: \"_value\")\n"
    }
   ]
  }
 ]
}