# Processor for duplicating detection frame metrics
#
# This is needed when the detection_frame_with_duration metric should be used
# both by the processors in the alert pipeline and by the output to InfluxDB.
# Without it, the InfluxDB output would be dependent on the other processors
# letting the metric pass through. By copying, we remove that dependency.
#
# Input: detection_frame_with_duration metrics
# Output:
# - detection_frame_with_duration
# - time_in_area_frame

[[processors.clone]]
  namepass = ["detection_frame_with_duration"]
  name_override = "time_in_area_frame"
