name: Prettier Format Check

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    env:
      # List of files patterns that should be formatted by prettier. This should normally include:
      # workflow files (yml) and any other json/yml/markdown files, including hidden config files for tools.
      PRETTIER_FILES: '"**/*.{json,yml,yaml,md}" ".github/**/*.{json,yml,yaml,md}" ".*.{yml,yaml}"'
      # Pin Prettier version to ensure deterministic CI runs and avoid unpredictable failures
      PRETTIER_VERSION: "3.6.0"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run prettier check
        run: |
          # Format JSON, YAML (including workflow files), and Markdown files
          npx prettier@${{ env.PRETTIER_VERSION }} --check ${{ env.PRETTIER_FILES }} --ignore-unknown

      - name: Get files that need formatting (on failure)
        if: failure() && github.event_name == 'pull_request'
        id: format_files
        run: |
          # Get list of files that need formatting
          FILES_NEEDING_FORMAT=$(npx prettier@${{ env.PRETTIER_VERSION }} --check ${{ env.PRETTIER_FILES }} --ignore-unknown --list-different 2>/dev/null || true)
          echo "files_list<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES_NEEDING_FORMAT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment on PR (on failure)
        if: failure() && github.event_name == 'pull_request' && steps.format_files.outputs.files_list != ''
        uses: actions/github-script@v7
        with:
          script: |
            const filesList = `${{ steps.format_files.outputs.files_list }}`.trim();

            if (filesList) {
              const files = filesList.split('\n').filter(f => f.trim());
              const comment = `## 🎨 Code Formatting Required

            Some files in this PR need to be formatted with Prettier.

            This includes JSON, YAML (workflow files), and Markdown files.

            **Files that need formatting:**
            ${files.map(file => `- \`${file}\``).join('\n')}

            **To fix this:**
            1. Format the files: \`npx prettier@${{ env.PRETTIER_VERSION }} --write ${{ env.PRETTIER_FILES }} --ignore-unknown\`
            2. Commit and push the changes

            The formatting check will automatically pass once these files are properly formatted.`;

              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
