name: Python Code Quality Check for the timelapse-s3 project

on:
  push:
    paths:
      - "project-timelapse-s3/test_scripts/**"
  pull_request:
    paths:
      - "project-timelapse-s3/test_scripts/**"

permissions:
  contents: read

jobs:
  python-quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project-timelapse-s3/test_scripts

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python Quality Check
        uses: ./.github/actions/python-quality-check
        with:
          working-directory: project-timelapse-s3/test_scripts
          additional-types: types-tqdm==4.67.0.20250516 types-boto3==1.40.4 types-Pillow==10.2.0.20240822
          # Disable E1101 for OpenCV false positives (no-member errors for cv2)
          pylint-options: --disable=E1101
